services:
  - type: web
    name: laravel-app
    env: docker
    plan: free
    dockerfilePath: ./Dockerfile
    buildCommand: ""
    startCommand: "apache2-foreground"
    envVars:
      - key: APP_ENV
        value: production
      - key: DB_CONNECTION
        value: mysql
      - key: DB_HOST
        value: metro.proxy.rlwy.net
      - key: DB_PORT
        value: 49596
      - key: DB_DATABASE
        value: railway
      - key: DB_USERNAME
        value: root
      - key: DB_PASSWORD
        value: yBoWgEAuSWUXyAHeCgPBIAjILGBizxmJ
      - key: APP_KEY
        value: base64:kfO4V4/BWCnbYkUWakOOvGXvnigwbOf8/t/L7IfrjMA=
